# Generated by Django 5.0.7 on 2026-07-26 12:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('name', models.CharField(max_length=150, verbose_name='نام دسته')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.productcategory', verbose_name='دسته والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی کالا',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای کالا',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('sku', models.CharField(blank=True, max_length=40, unique=True, verbose_name='کد کالا')),
                ('barcode', models.CharField(blank=True, max_length=40, verbose_name='بارکد')),
                ('name', models.CharField(max_length=200, verbose_name='نام کالا')),
                ('unit', models.CharField(choices=[('piece', 'عدد'), ('kg', 'کیلوگرم'), ('gram', 'گرم'), ('liter', 'لیتر'), ('meter', 'متر'), ('box', 'کارتن'), ('pack', 'بسته'), ('set', 'ست'), ('other', 'سایر')], default='piece', max_length=15, verbose_name='واحد شمارش')),
                ('purchase_price', models.DecimalField(decimal_places=0, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='قیمت خرید')),
                ('sale_price', models.DecimalField(decimal_places=0, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='قیمت فروش')),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='موجودی')),
                ('reorder_point', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='نقطه سفارش')),
                ('lead_time_days', models.PositiveIntegerField(default=7, verbose_name='زمان تأمین (روز)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='تصویر')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('default_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_products', to='parties.party', verbose_name='تأمین\u200cکننده پیش\u200cفرض')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.productcategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالاها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='مقدار (مثبت=ورود، منفی=خروج)')),
                ('unit_cost', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='بهای واحد')),
                ('reason', models.CharField(choices=[('purchase', 'خرید'), ('sale', 'فروش'), ('return_in', 'مرجوعی از مشتری'), ('return_out', 'مرجوعی به تأمین\u200cکننده'), ('adjustment', 'اصلاح موجودی'), ('waste', 'ضایعات'), ('initial', 'موجودی اولیه')], default='adjustment', max_length=20, verbose_name='علت')),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='موجودی پس از گردش')),
                ('source_type', models.CharField(blank=True, max_length=20, verbose_name='منبع')),
                ('source_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='شناسه منبع')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='catalog.product', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'گردش انبار',
                'verbose_name_plural': 'گردش\u200cهای انبار',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='catalog_pro_name_f603c0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='catalog_pro_sku_2c4c34_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', 'date'], name='catalog_sto_product_01c91c_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['source_type', 'source_id'], name='catalog_sto_source__3217b6_idx'),
        ),
    ]
