# Generated by Django 5.0.7 on 2026-08-09 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('reason', models.TextField(verbose_name='علت خرابی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('registered_at', models.DateField(verbose_name='تاریخ ثبت')),
                ('last_follow_up_at', models.DateField(blank=True, null=True, verbose_name='تاریخ آخرین پیگیری')),
                ('status', models.CharField(choices=[('open', 'خراب'), ('repaired', 'درست شده')], default='open', max_length=20, verbose_name='وضعیت')),
                ('repaired_at', models.DateField(blank=True, null=True, verbose_name='تاریخ درست شدن')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_defects', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='catalog.product', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'کالای خراب',
                'verbose_name_plural': 'کالاهای خراب',
                'ordering': ['-registered_at', '-id'],
                'indexes': [models.Index(fields=['status', 'registered_at'], name='catalog_pro_status_9dd264_idx'), models.Index(fields=['product', 'status'], name='catalog_pro_product_a781f8_idx')],
            },
        ),
    ]
