# Generated by Django 5.0.7 on 2026-08-16 07:30

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_defect'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('serial_number', models.CharField(max_length=80, verbose_name='شماره سریال')),
                ('status', models.CharField(choices=[('in_stock', 'موجود'), ('sold', 'فروخته\u200cشده')], default='in_stock', max_length=15, verbose_name='وضعیت')),
                ('purchase_order_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='سفارش خرید')),
                ('sale_order_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='سفارش فروش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serials', to='catalog.product', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'سریال کالا',
                'verbose_name_plural': 'سریال\u200cهای کالا',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['serial_number'], name='catalog_pro_serial__cae632_idx'), models.Index(fields=['product', 'status'], name='catalog_pro_product_dc02fa_idx'), models.Index(fields=['purchase_order_id'], name='catalog_pro_purchas_abee72_idx'), models.Index(fields=['sale_order_id'], name='catalog_pro_sale_or_3318f9_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='productserial',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('serial_number'), name='catalog_productserial_serial_ci_uniq'),
        ),
    ]
