# Generated by Django 5.0.7 on 2026-08-16 08:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_serial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productdefect',
            name='serial_number',
            field=models.CharField(blank=True, max_length=80, verbose_name='شماره سریال'),
        ),
        migrations.AlterField(
            model_name='productserial',
            name='status',
            field=models.CharField(choices=[('in_stock', 'موجود'), ('sold', 'فروخته\u200cشده'), ('defective', 'خراب')], default='in_stock', max_length=15, verbose_name='وضعیت'),
        ),
        migrations.AddIndex(
            model_name='productdefect',
            index=models.Index(fields=['serial_number'], name='catalog_pro_serial__9581d7_idx'),
        ),
    ]
