# Generated by Django 5.0.7 on 2026-07-26 12:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('number', models.CharField(blank=True, max_length=25, unique=True, verbose_name='شماره سفارش')),
                ('order_type', models.CharField(choices=[('sale', 'فروش'), ('purchase', 'خرید')], default='sale', max_length=15, verbose_name='نوع سفارش')),
                ('order_date', models.DateField(verbose_name='تاریخ سفارش')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='مهلت پرداخت / تحویل')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('confirmed', 'تأیید شده'), ('partial', 'تحویل جزئی'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='draft', max_length=15, verbose_name='وضعیت')),
                ('payment_status', models.CharField(choices=[('unpaid', 'پرداخت نشده'), ('partial', 'پرداخت جزئی'), ('paid', 'تسویه شده')], default='unpaid', max_length=15, verbose_name='وضعیت پرداخت')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='تخفیف')),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد مالیات')),
                ('shipping_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='هزینه ارسال')),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='جمع اقلام')),
                ('tax_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مبلغ مالیات')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مبلغ نهایی')),
                ('paid_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مبلغ پرداخت\u200cشده')),
                ('cost_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='بهای تمام\u200cشده اقلام')),
                ('affects_stock', models.BooleanField(default=True, verbose_name='اثر روی موجودی انبار')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تأیید')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_orders', to=settings.AUTH_USER_MODEL, verbose_name='تأییدکننده')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='parties.party', verbose_name='طرف حساب')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'ordering': ['-order_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='مقدار')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='قیمت واحد')),
                ('unit_cost', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='بهای واحد')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='تخفیف ردیف')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیح')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'ردیف سفارش',
                'verbose_name_plural': 'ردیف\u200cهای سفارش',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('suggested_date', models.DateField(verbose_name='تاریخ پیشنهادی سفارش')),
                ('suggested_quantity', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='مقدار پیشنهادی')),
                ('estimated_cost', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='هزینه تقریبی')),
                ('avg_daily_sales', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='میانگین فروش روزانه')),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='موجودی فعلی')),
                ('days_of_stock_left', models.DecimalField(decimal_places=1, default=0, max_digits=8, verbose_name='روز باقی\u200cمانده تا اتمام موجودی')),
                ('stockout_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تخمینی اتمام موجودی')),
                ('coverage_days', models.PositiveIntegerField(default=30, verbose_name='روز پوشش هدف')),
                ('lead_time_days', models.PositiveIntegerField(default=7, verbose_name='زمان تأمین')),
                ('best_weekday', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='پرفروش\u200cترین روز هفته')),
                ('seasonality_factor', models.DecimalField(decimal_places=3, default=1, max_digits=6, verbose_name='ضریب فصلی')),
                ('trend_percent', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='درصد روند رشد')),
                ('confidence', models.PositiveSmallIntegerField(default=0, verbose_name='درصد اطمینان')),
                ('data_points', models.PositiveIntegerField(default=0, verbose_name='تعداد داده تحلیل\u200cشده')),
                ('priority', models.CharField(choices=[('critical', 'بحرانی'), ('high', 'بالا'), ('medium', 'متوسط'), ('low', 'پایین')], default='medium', max_length=15, verbose_name='اولویت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('accepted', 'پذیرفته شده'), ('rejected', 'رد شده'), ('ordered', 'سفارش ثبت شد'), ('expired', 'منقضی شده')], default='pending', max_length=15, verbose_name='وضعیت')),
                ('reason', models.TextField(blank=True, verbose_name='دلیل پیشنهاد')),
                ('analysis', models.JSONField(blank=True, default=dict, verbose_name='جزئیات تحلیل')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان تولید')),
                ('review_note', models.TextField(blank=True, verbose_name='یادداشت بررسی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='catalog.product', verbose_name='کالا')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_suggestions', to=settings.AUTH_USER_MODEL, verbose_name='بررسی\u200cکننده')),
                ('suggested_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='parties.party', verbose_name='تأمین\u200cکننده پیشنهادی')),
            ],
            options={
                'verbose_name': 'پیشنهاد هوشمند',
                'verbose_name_plural': 'پیشنهادهای هوشمند',
                'ordering': ['suggested_date', '-priority'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='source_suggestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_orders', to='orders.purchasesuggestion', verbose_name='پیشنهاد مبدأ'),
        ),
        migrations.CreateModel(
            name='SalesImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('file_name', models.CharField(max_length=255, verbose_name='نام فایل')),
                ('file', models.FileField(blank=True, null=True, upload_to='sales_imports/', verbose_name='فایل')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('done', 'انجام شده'), ('failed', 'ناموفق')], default='pending', max_length=15, verbose_name='وضعیت')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='تعداد کل ردیف')),
                ('imported_rows', models.PositiveIntegerField(default=0, verbose_name='ردیف\u200cهای وارد\u200cشده')),
                ('skipped_rows', models.PositiveIntegerField(default=0, verbose_name='ردیف\u200cهای رد\u200cشده')),
                ('created_products', models.PositiveIntegerField(default=0, verbose_name='کالاهای ساخته\u200cشده')),
                ('errors', models.JSONField(blank=True, default=list, verbose_name='خطاها')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='از تاریخ')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='تا تاریخ')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_imports', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'بارگذاری فروش گذشته',
                'verbose_name_plural': 'بارگذاری\u200cهای فروش گذشته',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('product_name_raw', models.CharField(max_length=255, verbose_name='نام کالا در فایل')),
                ('sale_date', models.DateField(verbose_name='تاریخ فروش')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='مقدار')),
                ('unit_price', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='قیمت واحد')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مبلغ کل')),
                ('unit_cost', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='بهای واحد')),
                ('customer_name', models.CharField(blank=True, max_length=200, verbose_name='نام مشتری')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_history', to='parties.party', verbose_name='طرف حساب')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_history', to='catalog.product', verbose_name='کالا')),
                ('source_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_records', to='orders.order', verbose_name='سفارش مبدأ')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='orders.salesimportbatch', verbose_name='دسته ورود')),
            ],
            options={
                'verbose_name': 'سابقه فروش',
                'verbose_name_plural': 'سوابق فروش',
                'ordering': ['-sale_date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='purchasesuggestion',
            index=models.Index(fields=['status', 'suggested_date'], name='orders_purc_status_8cdc74_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasesuggestion',
            index=models.Index(fields=['product'], name='orders_purc_product_e1637d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_type', 'status'], name='orders_orde_order_t_1378c7_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_date'], name='orders_orde_order_d_d71205_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['party'], name='orders_orde_party_i_e178fc_idx'),
        ),
        migrations.AddIndex(
            model_name='saleshistory',
            index=models.Index(fields=['product', 'sale_date'], name='orders_sale_product_cecf8a_idx'),
        ),
        migrations.AddIndex(
            model_name='saleshistory',
            index=models.Index(fields=['sale_date'], name='orders_sale_sale_da_8a4223_idx'),
        ),
    ]
