# Generated by Django 5.0.7 on 2026-08-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_entry_mode_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='serial_number',
            field=models.CharField(blank=True, max_length=80, verbose_name='شماره سریال'),
        ),
    ]
