# Generated by Django 5.0.7 on 2026-07-26 12:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
        ('orders', '0001_initial'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('direction', models.CharField(choices=[('payable', 'پرداختی'), ('receivable', 'دریافتی')], max_length=15, verbose_name='نوع چک')),
                ('serial_number', models.CharField(max_length=30, verbose_name='شماره چک')),
                ('sayad_id', models.CharField(blank=True, max_length=16, verbose_name='شناسه صیادی')),
                ('bank_name', models.CharField(choices=[('melli', 'بانک ملی ایران'), ('sepah', 'بانک سپه'), ('tejarat', 'بانک تجارت'), ('mellat', 'بانک ملت'), ('saderat', 'بانک صادرات ایران'), ('keshavarzi', 'بانک کشاورزی'), ('maskan', 'بانک مسکن'), ('sanat_madan', 'بانک صنعت و معدن'), ('refah', 'بانک رفاه کارگران'), ('post', 'پست بانک ایران'), ('tosee_saderat', 'بانک توسعه صادرات'), ('tosee_taavon', 'بانک توسعه تعاون'), ('parsian', 'بانک پارسیان'), ('pasargad', 'بانک پاسارگاد'), ('saman', 'بانک سامان'), ('sina', 'بانک سینا'), ('shahr', 'بانک شهر'), ('dey', 'بانک دی'), ('ansar', 'بانک انصار'), ('eghtesad_novin', 'بانک اقتصاد نوین'), ('karafarin', 'بانک کارآفرین'), ('gardeshgari', 'بانک گردشگری'), ('iran_zamin', 'بانک ایران زمین'), ('ayandeh', 'بانک آینده'), ('resalat', 'بانک قرض\u200cالحسنه رسالت'), ('mehr_iran', 'بانک قرض\u200cالحسنه مهر ایران'), ('khavarmiane', 'بانک خاورمیانه'), ('sarmayeh', 'بانک سرمایه'), ('other', 'سایر')], default='other', max_length=30, verbose_name='بانک')),
                ('branch', models.CharField(blank=True, max_length=120, verbose_name='شعبه')),
                ('account_number', models.CharField(blank=True, max_length=40, verbose_name='شماره حساب')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='مبلغ')),
                ('issue_date', models.DateField(verbose_name='تاریخ صدور')),
                ('due_date', models.DateField(verbose_name='تاریخ سرسید')),
                ('holder_name', models.CharField(blank=True, max_length=200, verbose_name='در وجه / صاحب چک')),
                ('status', models.CharField(choices=[('in_portfolio', 'در جریان'), ('submitted', 'واگذار شده به بانک'), ('cleared', 'وصول شده'), ('bounced', 'برگشتی'), ('returned', 'عودت داده شده'), ('transferred', 'واگذار به غیر (خرج شده)'), ('extended', 'تمدید شده'), ('cancelled', 'ابطال شده')], default='in_portfolio', max_length=20, verbose_name='وضعیت')),
                ('settled_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تعیین وضعیت نهایی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='cheques/', verbose_name='تصویر چک')),
                ('create_ledger_entry', models.BooleanField(default=True, verbose_name='ثبت خودکار در دفتر طرف حساب')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques', to='ledger.bankaccount', verbose_name='حساب بانکی فروشگاه')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cheques', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques', to='orders.order', verbose_name='سفارش مرتبط')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cheques', to='parties.party', verbose_name='طرف حساب')),
            ],
            options={
                'verbose_name': 'چک',
                'verbose_name_plural': 'چک\u200cها',
                'ordering': ['due_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChequeStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('from_status', models.CharField(blank=True, choices=[('in_portfolio', 'در جریان'), ('submitted', 'واگذار شده به بانک'), ('cleared', 'وصول شده'), ('bounced', 'برگشتی'), ('returned', 'عودت داده شده'), ('transferred', 'واگذار به غیر (خرج شده)'), ('extended', 'تمدید شده'), ('cancelled', 'ابطال شده')], max_length=20, verbose_name='وضعیت قبلی')),
                ('to_status', models.CharField(choices=[('in_portfolio', 'در جریان'), ('submitted', 'واگذار شده به بانک'), ('cleared', 'وصول شده'), ('bounced', 'برگشتی'), ('returned', 'عودت داده شده'), ('transferred', 'واگذار به غیر (خرج شده)'), ('extended', 'تمدید شده'), ('cancelled', 'ابطال شده')], max_length=20, verbose_name='وضعیت جدید')),
                ('changed_at_date', models.DateField(verbose_name='تاریخ رویداد')),
                ('note', models.TextField(blank=True, verbose_name='یادداشت')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheque_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('cheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='cheques.cheque', verbose_name='چک')),
            ],
            options={
                'verbose_name': 'تاریخچه وضعیت چک',
                'verbose_name_plural': 'تاریخچه وضعیت چک\u200cها',
                'ordering': ['-changed_at_date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='cheque',
            index=models.Index(fields=['direction', 'status'], name='cheques_che_directi_2d56f9_idx'),
        ),
        migrations.AddIndex(
            model_name='cheque',
            index=models.Index(fields=['due_date'], name='cheques_che_due_dat_61d88f_idx'),
        ),
        migrations.AddIndex(
            model_name='cheque',
            index=models.Index(fields=['party'], name='cheques_che_party_i_6eb256_idx'),
        ),
        migrations.AddConstraint(
            model_name='cheque',
            constraint=models.UniqueConstraint(fields=('direction', 'bank_name', 'serial_number'), name='unique_cheque_serial_per_bank_direction'),
        ),
    ]
