# Generated by Django 5.0.7 on 2026-07-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='کد طرف حساب')),
                ('name', models.CharField(max_length=200, verbose_name='نام / عنوان')),
                ('party_type', models.CharField(choices=[('customer', 'مشتری'), ('supplier', 'تأمین\u200cکننده'), ('both', 'مشتری و تأمین\u200cکننده'), ('other', 'سایر')], default='customer', max_length=20, verbose_name='نوع طرف حساب')),
                ('is_legal_entity', models.BooleanField(default=False, verbose_name='شخص حقوقی')),
                ('national_id', models.CharField(blank=True, max_length=20, verbose_name='کد ملی / شناسه ملی')),
                ('economic_code', models.CharField(blank=True, max_length=20, verbose_name='کد اقتصادی')),
                ('mobile', models.CharField(blank=True, max_length=15, verbose_name='موبایل')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='شهر')),
                ('address', models.TextField(blank=True, verbose_name='نشانی')),
                ('postal_code', models.CharField(blank=True, max_length=12, verbose_name='کد پستی')),
                ('opening_balance', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مانده اولیه (مثبت = بدهکار)')),
                ('credit_limit', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='سقف اعتبار')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
            ],
            options={
                'verbose_name': 'طرف حساب',
                'verbose_name_plural': 'طرف\u200cهای حساب',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='parties_par_name_645a31_idx'), models.Index(fields=['party_type'], name='parties_par_party_t_8323a0_idx')],
            },
        ),
    ]
