# Generated by Django 5.0.7 on 2026-07-26 12:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان حساب')),
                ('bank_name', models.CharField(max_length=100, verbose_name='نام بانک')),
                ('account_number', models.CharField(blank=True, max_length=40, verbose_name='شماره حساب')),
                ('iban', models.CharField(blank=True, max_length=30, verbose_name='شبا')),
                ('card_number', models.CharField(blank=True, max_length=20, verbose_name='شماره کارت')),
                ('branch', models.CharField(blank=True, max_length=120, verbose_name='شعبه')),
                ('initial_balance', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='موجودی اولیه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'حساب بانکی',
                'verbose_name_plural': 'حساب\u200cهای بانکی',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='FinanceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('name', models.CharField(max_length=120, verbose_name='نام دسته')),
                ('kind', models.CharField(choices=[('expense', 'هزینه'), ('income', 'درآمد')], default='expense', max_length=10, verbose_name='نوع')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'دسته هزینه/درآمد',
                'verbose_name_plural': 'دسته\u200cهای هزینه و درآمد',
                'ordering': ['kind', 'name'],
                'unique_together': {('name', 'kind')},
            },
        ),
        migrations.CreateModel(
            name='FinanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('kind', models.CharField(choices=[('expense', 'هزینه'), ('income', 'درآمد')], default='expense', max_length=10, verbose_name='نوع')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='مبلغ')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدی'), ('card', 'کارت به کارت'), ('transfer', 'حواله بانکی'), ('cheque', 'چک'), ('other', 'سایر')], default='cash', max_length=20, verbose_name='روش پرداخت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='finance/', verbose_name='پیوست')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_records', to='ledger.bankaccount', verbose_name='حساب بانکی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='ledger.financecategory', verbose_name='دسته')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_records', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_records', to='parties.party', verbose_name='طرف حساب')),
            ],
            options={
                'verbose_name': 'هزینه / درآمد',
                'verbose_name_plural': 'هزینه\u200cها و درآمدها',
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['kind', 'date'], name='ledger_fina_kind_b60c0a_idx'), models.Index(fields=['date'], name='ledger_fina_date_0fefb9_idx')],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('debit', models.DecimalField(decimal_places=0, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='بدهکار')),
                ('credit', models.DecimalField(decimal_places=0, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='بستانکار')),
                ('category', models.CharField(choices=[('opening', 'مانده اولیه'), ('sale_invoice', 'فاکتور فروش'), ('purchase_invoice', 'فاکتور خرید'), ('cash_receipt', 'دریافت نقدی'), ('cash_payment', 'پرداخت نقدی'), ('cheque_received', 'دریافت چک'), ('cheque_issued', 'صدور چک'), ('cheque_cleared', 'وصول چک'), ('cheque_bounced', 'برگشت چک'), ('discount', 'تخفیف'), ('return', 'مرجوعی'), ('adjustment', 'تعدیل حساب'), ('other', 'سایر')], default='other', max_length=30, verbose_name='بابت')),
                ('document_number', models.CharField(blank=True, max_length=50, verbose_name='شماره سند')),
                ('description', models.TextField(blank=True, verbose_name='شرح')),
                ('source_type', models.CharField(choices=[('manual', 'ثبت دستی'), ('order', 'سفارش'), ('cheque', 'چک'), ('finance', 'هزینه/درآمد')], default='manual', max_length=20, verbose_name='منبع')),
                ('source_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='شناسه منبع')),
                ('is_system_generated', models.BooleanField(default=False, verbose_name='تولید سیستمی')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='ledger.bankaccount', verbose_name='حساب بانکی')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='parties.party', verbose_name='طرف حساب')),
            ],
            options={
                'verbose_name': 'سند بدهکار/بستانکار',
                'verbose_name_plural': 'اسناد بدهکار/بستانکار',
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['party', 'date'], name='ledger_ledg_party_i_547dd0_idx'), models.Index(fields=['date'], name='ledger_ledg_date_f3a643_idx'), models.Index(fields=['source_type', 'source_id'], name='ledger_ledg_source__f6b4db_idx')],
            },
        ),
    ]
